server:
  port: 8080

spring:
  datasource: # JDBC DB 접속 정보
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inaction?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa: # JPA 설정
    hibernate:
      ddl-auto: create
    show-sql: true # 쿼리 보기
    format-sql: true # 쿼리 포맷팅
    use_sql_comments: true # 쿼리 주석
    type:
      descriptor:
        sql: trace
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞는 dialect 설정
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html

